rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  consumer:
    queue_name: document_sender
    exchange: ""
  producer:
    queue_name: document_saver
    exchange: ""

s3:
  bucket: "diplom.clusterization"