app:
  name: 'clusterlizer'
  version: '1.0.0'
  address: localhost:8080

logger:
  log_level: 'debug'

front:
  static: './front'

rabbitmq:
  producer:
    document_name_sender:
      url: amqp://guest:guest@localhost:5672/
      queue_name: document_sender
      exchange:

  consumer:
    document_saver:
      url: amqp://guest:guest@localhost:5672/
      queue_name: document_saver
      exchange:


postgres:
  pool_max: 10
  username: diplom
  db: diplom
  password: diplom
  host: localhost
  port: 5432

s3:
  bucket: diplom.clusterization
