app:
  name: 'clusterlizer'
  version: '1.0.0'
  port: 8080

logger:
  log_level: 'debug'

front:
  static: './front'

kafka:
  consumer:
    document_sender:
      url: localhost:9092
      topic: document_sender
#      max_bytes: 10**20
      group: document_sender-group-a
  producer:
    document_saver:
      url: localhost:9092
      topic: document_sender
      max_bytes: 10mb

postgres:
  pool_max: 10
  username: diplom
  db: diplom
  password: diplom
  host: localhost
  port: 6432
