app:
  name: 'clusterlizer'
  version: '1.0.0'
  port: 8080

logger:
  log_level: 'debug'

front:
  static: './front'

kafka:
  producer:
    document_name_sender:
      url: kafka:9092
      topic: document_sender
#      max_bytes: 10**20
      group: document_sender-group-a
  consumer:
    document_saver:
      url: localhost:9092
      topic: document_sender
#      max_bytes: 10mb

rabbitmq:
  producer:
    document_name_sender:
      url: amqp://guest:guest@localhost:5672/
      queue_name: document_sender

  consumer:
    document_saver:
      url: localhost:9092
      queue_name: document_saver

postgres:
  pool_max: 10
  username: diplom
  db: diplom
  password: diplom
  host: localhost
  port: 5432

s3:
  bucket: diplom.clusterization
